import type { NextPage } from "next";
import { signIn, signOut } from "next-auth/react";
import Head from "next/head";
import { trpc } from "utils/trpc";

// Avoid useProvider call because only twitter is used as provider
const TWITTER_PROVIDER_ID = "twitter";

const Home: NextPage = () => {
    const { data: session } = trpc.nextAuth.getSession.useQuery(undefined, {
        suspense: true,
    });

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className=""
        style={{ display: "grid", placeItems: "center", height: "100vh" }}
      >
        <button
          style={{ height: "4rem", width: "8rem", fontSize: "1.5rem" }}
          onClick={
            session
              ? () => {
                  signOut();
                }
              : () => {
                  signIn(TWITTER_PROVIDER_ID, {
                    callbackUrl: `/dashboard`,
                  });
                }
          }
        >
          {session ? "Sign Out" : "Sign In"}
        </button>
      </main>
    </div>
  );
};

export default Home;
