import type { NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";

// Avoid useProvider call because only twitter is used as provider
const TWITTER_PROVIDER_ID = "twitter";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  const handleLogin = () => {
    signIn(TWITTER_PROVIDER_ID, {
      callbackUrl: `/${session?.user?.userName}`,
    });
  };

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className=""
        style={{ display: "grid", placeItems: "center", height: "100vh" }}
      >
        <button
          id="login"
          style={{ height: "4rem", width: "8rem", fontSize: "2rem" }}
          onClick={handleLogin}
          disabled={status === "authenticated"}
        >
          Login
        </button>
      </main>
    </div>
  );
};

export default Home;
